[workspace]
members = [
    "core",
    "wrappers",
    "utils/hash_db",
    "utils/trie_db",
    "utils/trie_map",
    "utils/slot_db",
]
resolver = "2"

[workspace.dependencies]
ruc = "5.1.2"
rand = "0.8.5"
once_cell = "1.13.1"
parking_lot = "0.12.1"

bcs = { version = "0.1.5" }
rmp-serde = { version = "1.1.1" }
serde_json = { version = "1.0.87" }
serde = { version = "1.0.136", features = ["derive"] }

threadpool = "1.8.1" # used in a background cleaner

primitive-types-0-12 = { package = "primitive-types", version = "0.12", default-features = false }
primitive-types-0-11 = { package = "primitive-types", version = "0.11", default-features = false }
primitive-types-0-10 = { package = "primitive-types", version = "0.10", default-features = false }

parity-db = "0.4.13"
rocksdb = { version = "0.22.0", default-features = false }

keccak-hasher = "0.16.0"
hash-db = "0.16.0"
trie-db-fun = { version = "100.28.0" }
reference-trie-fun = { version = "100.29.1" }

mmdb = { path = "wrappers", version = "0.62.0", default-features = false }
mmdb_core = { path = "core", version = "0.62.0", default-features = false }

mmdb_trie_db = { path = "utils/trie_db", version = "0.21.0", default-features = false }
mmdb_hash_db = { path = "utils/hash_db", version = "0.21.0", default-features = false }
