[workspace]
members = [
    "core",
    "wrappers",
    "utils/hash_db",
    "utils/trie_db",
    "utils/slot_db",
]
resolver = "2"

[workspace.dependencies]
ruc = "6.0.0"
rand = "0.8.5"
once_cell = "1.13.1"
parking_lot = "0.12.1"

serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.87" }
msgpack = { package = "rmp-serde", version = "1.1.1" }
parity-scale-codec = "3.6.12"

threadpool = "1.8.1" # used in a background cleaner

parity-db = "0.4.13"
rocksdb = { version = "0.22.0", default-features = false }

keccak-hasher = "0.16.0"
hash-db = "0.16.0"
trie-db = "0.29.1"
trie-root = "0.18.0"

mmdb = { path = "wrappers", version = "1.1.0", default-features = false }
mmdb_core = { path = "core", version = "1.0.0", default-features = false }

mmdb_trie_db = { path = "utils/trie_db", version = "0.3.0", default-features = false }
mmdb_hash_db = { path = "utils/hash_db", version = "0.3.0", default-features = false }
